персона(vladimir_lvov, "Владимир Львов", "м").
персона(gavriil_odinets, "Гавриил Одинец", "м").
персона(vatslav_vorovskii, "Вацлав Воровский", "м").
персона(dmitrii_merezhkovskii, "Дмитрий Мережковский", "м").
персона(romola_nizhinskaya, "Ромола Нижинская", "ж").
персона(tatyana_shchepkina_kupernik, "Татьяна Щепкина-Куперник", "ж").
персона(lev_anninskii, "Лев Аннинский", "м").
персона(anastasiya_gendrikova, "Анастасия Гендрикова", "ж").
персона(vsevolod_meierkhold, "Всеволод Мейерхольд", "м").
персона(iraklii_tsereteli, "Ираклий Церетели", "м").
персона(abram_gots, "Абрам Гоц", "м").
персона(grigorii_zinovev, "Григорий Зиновьев", "м").
персона(ilya_erenburg, "Илья Эренбург", "м").
персона(leonid_andreev, "Леонид Андреев", "м").
персона(anatolii_mariengof, "Анатолий Мариенгоф", "м").
персона(boris_anrep, "Борис Анреп", "м").
персона(mikhail_pokrovskii, "Михаил Покровский", "м").
персона(nikolai_kovalevskii, "Николай Ковалевский", "м").
персона(feliks_dzerzhinskii, "Феликс Дзержинский", "м").
персона(aleksandr_spiridovich, "Александр Спиридович", "м").
персона(vladimir_telyakovskii, "Владимир Теляковский", "м").
персона(anton_denikin, "Антон Деникин", "м").
персона(olga_ravich, "Ольга Равич", "ж").
персона(fedor_sologub, "Федор Сологуб", "м").
персона(matilda_kshesinskaya, "Матильда Кшесинская", "ж").
персона(lavr_kornilov, "Лавр Корнилов", "м").
персона(aleksandr_protopopov, "Александр Протопопов", "м").
персона(vladislav_khodasevich, "Владислав Ходасевич", "м").
персона(osip_brik, "Осип Брик", "м").
персона(vladimir_nabokov, "Владимир Набоков", "м").
персона(nina_andreevskaya, "Нина Андреевская", "ж").
персона(sofya_omirova, "Софья Омирова", "ж").
персона(pavel_ryabushinskii, "Павел Рябушинский", "м").
персона(nina_petrovskaya, "Нина Петровская", "ж").
персона(sergei_sudeikin, "Сергей Судейкин", "м").
персона(anna_petrova_vodkina, "Анна Петрова-Водкина", "ж").
персона(lyubov_chernisheva, "Любовь Чернышева", "ж").
персона(yelena_vinograd, "Елена Виноград", "ж").
персона(rene_peter, "Рене Петер", "м").
персона(rozaliya_plekhanova, "Розалия Плеханова", "ж").
персона(nadezhda_udaltsova, "Надежда Удальцова", "ж").
персона(mariya_chukovskaya, "Мария Чуковская", "ж").
персона(olga_spesivtseva, "Ольга Спесивцева", "ж").
персона(vladimir_sakharov, "Владимир Сахаров", "м").
персона(pavel_malyantovich, "Павел Малянтович", "м").
персона(natalya_goncharova, "Наталья Гончарова", "ж").
персона(sergei_oldenburg, "Сергей Ольденбург", "м").
персона(yurii_yurev, "Юрий Юрьев", "м").
персона(lev_bakst, "Лев Бакст", "м").
персона(nikolai_klyuev, "Николай Клюев", "м").
персона(innokentii_annenskii, "Иннокентий Анненский", "м").
персона(igor_grabar, "Игорь Грабарь", "м").
персона(mikhail_larionov, "Михаил Ларионов", "м").
персона(konstantin_oberuchev, "Константин Оберучев", "м").
персона(sofya_dzerzhinskaya, "Софья Дзержинская", "ж").
персона(arkadii_averchenko, "Аркадий Аверченко", "м").
персона(yekaterina_zagorskaya_paustovskaya, "Екатерина Загорская-Паустовская", "ж").
персона(sergei_rakhmaninov, "Сергей Рахманинов", "м").
персона(mikhail_prishvin, "Михаил Пришвин", "м").
персона(yekaterina_butovich, "Екатерина Бутович", "ж").
персона(petr_rutenberg, "Петр Рутенберг", "м").
персона(georgii_safarov, "Георгий Сафаров", "м").
персона(anatolii_lunacharskii, "Анатолий Луначарский", "м").
персона(vladimir_gilyarovskii, "Владимир Гиляровский", "м").
персона(igor_severyanin, "Игорь Северянин", "м").
персона(vera_zasulich, "Вера Засулич", "ж").
персона(vasilii_rozanov, "Василий Розанов", "м").
персона(aleksandr_shlyapnikov, "Александр Шляпников", "м").
персона(dmitrii_ryabushinskii, "Дмитрий Рябушинский", "м").
персона(sergei_gusev, "Сергей Гусев", "м").
персона(nikolai_aseev, "Николай Асеев", "м").
персона(nikolai_golitsin, "Николай Голицын", "м").
персона(georgii_adamovich, "Георгий Адамович", "м").
персона(nikolai_galagan, "Николай Галаган", "м").
персона(stepan_ryabushinskii, "Степан Рябушинский", "м").
персона(mikhail_zenkevich, "Михаил Зенкевич", "м").
персона(vladimir_vinnichenko, "Владимир Винниченко", "м").
персона(mikhail_nikolaev, "Михаил Николаев", "м").
персона(aleksandr_amfiteatrov, "Александр Амфитеатров", "м").
персона(ida_rubinshtein, "Ида Рубинштейн", "ж").
персона(pavel_akselrod, "Павел Аксельрод", "м").
персона(aleksei_volkov, "Алексей Волков", "м").
персона(lev_trotskii, "Лев Троцкий", "м").
персона(vasilii_luzhskii, "Василий Лужский", "м").
персона(aleksandra_tolstaya, "Александра Толстая", "ж").
персона(petr_petrov, "Петр Петров", "м").
персона(vladimir_orlov, "Владимир Орлов", "м").
персона(maks_gofman, "Макс Гофман", "м").
персона(ilya_fondaminskii, "Илья Фондаминский", "м").
персона(petr_polovtsov, "Петр Половцов", "м").
персона(sofiya_klyachko, "София Клячко", "ж").
персона(anna_turgeneva, "Анна Тургенева", "ж").
персона(sergei_dyagilev, "Сергей Дягилев", "м").
персона(olga_palei, "Ольга Палей", "ж").
персона(yevgeniya_sumenson, "Евгения Суменсон", "ж").
персона(mikhail_kuzmin, "Михаил Кузмин", "м").
персона(vera_guchkova, "Вера Гучкова", "ж").
персона(maksim_gorkii, "Максим Горький", "м").
персона(konstantin_nilov, "Константин Нилов", "м").
персона(yelizaveta_kuzmina_karavaeva, "Елизавета Кузьмина-Караваева", "ж").
персона(vladimir_chertkov, "Владимир Чертков", "м").
персона(viktor_chernov, "Виктор Чернов", "м").
персона(velikii_knyaz_mikhail_aleksandrovich, "Великий князь Михаил Александрович", "м").
персона(vladimir_amfiteatrov_kadashev, "Владимир Амфитеатров-Кадашев", "м").
персона(stanislav_lazovert, "Станислав Лазоверт", "м").
персона(vlas_doroshevich, "Влас Дорошевич", "м").
персона(mikhail_gershenzon, "Михаил Гершензон", "м").
персона(aleksandr_zhirkevich, "Александр Жиркевич", "м").
персона(ariadna_tirkova_vilyams, "Ариадна Тыркова-Вильямс", "ж").
персона(mikhail_lozinskii, "Михаил Лозинский", "м").
персона(konstantin_balmont, "Константин Бальмонт", "м").
персона(boris_engelgardt, "Борис Энгельгардт", "м").
персона(sofiya_buksgevden, "София Буксгевден", "ж").
персона(petr_vrangel, "Петр Врангель", "м").
персона(aleksandr_kizevetter, "Александр Кизеветтер", "м").
персона(vasilii_kandinskii, "Василий Кандинский", "м").
персона(el_lisitskii, "Эль Лисицкий", "м").
персона(ivan_yefremov, "Иван Ефремов", "м").
персона(yevgenii_chikalenko, "Евгений Чикаленко", "м").
персона(boris_shtyurmer, "Борис Штюрмер", "м").
персона(valentina_grabar, "Валентина Грабарь", "ж").
персона(boris_kustodiev, "Борис Кустодиев", "м").
персона(vera_sinyakova, "Вера Синякова", "ж").
персона(vladimir_mayakovskii, "Владимир Маяковский", "м").
персона(olga_knipper_chekhova, "Ольга Книппер-Чехова", "ж").
персона(sergei_bulgakov, "Сергей Булгаков", "м").
персона(yevgenii_trubetskoi, "Евгений Трубецкой", "м").
персона(viktor_vasnetsov, "Виктор Васнецов", "м").
персона(aleksei_kruchenikh, "Алексей Крученых", "м").
персона(nikolai_pokrovskii, "Николай Покровский", "м").
персона(lev_kamenev, "Лев Каменев", "м").
персона(yelena_tsvetkovskaya, "Елена Цветковская", "ж").
персона(leonid_sobinov, "Леонид Собинов", "м").
персона(boris_pasternak, "Борис Пастернак", "м").
персона(aleksandr_ziloti, "Александр Зилоти", "м").
персона(erikh_lyudendorf, "Эрих Людендорф", "м").
персона(lyubov_mendeleeva_blok, "Любовь Менделеева-Блок", "ж").
персона(aleksandr_parvus, "Александр Парвус", "м").
персона(natalya_palei, "Наталья Палей", "ж").
персона(irina_odoevtseva, "Ирина Одоевцева", "ж").
персона(yevgenii_kobilinskii, "Евгений Кобылинский", "м").
персона(yelizaveta_efron, "Елизавета Эфрон", "ж").
персона(roman_yakobson, "Роман Якобсон", "м").
персона(lev_tikhomirov, "Лев Тихомиров", "м").
персона(aleksandr_tairov, "Александр Таиров", "м").
персона(vasilii_maklakov, "Василий Маклаков", "м").
персона(vyacheslav_ivanov, "Вячеслав Иванов", "м").
персона(ivan_bilibin, "Иван Билибин", "м").
персона(andrei_bakst, "Андрей Бакст", "м").
персона(anna_benua, "Анна Бенуа", "ж").
персона(aleksandr_bublikov, "Александр Бубликов", "м").
персона(mikhail_osorgin, "Михаил Осоргин", "м").
персона(mariya_yelenevskaya, "Мария Еленевская", "ж").
персона(simon_petlyura, "Симон Петлюра", "м").
персона(igor_stravinskii, "Игорь Стравинский", "м").
персона(yakov_glinka, "Яков Глинка", "м").
персона(aleksandr_guchkov, "Александр Гучков", "м").
персона(benedikt_livshits, "Бенедикт Лившиц", "м").
персона(nikolai_berdyaev, "Николай Бердяев", "м").
персона(ariadna_efron, "Ариадна Эфрон", "ж").
персона(yevgenii_vakhtangov, "Евгений Вахтангов", "м").
персона(georgii_lvov, "Георгий Львов", "м").
персона(nadezhda_krupskaya, "Надежда Крупская", "ж").
персона(karl_radek, "Карл Радек", "м").
персона(nikolai_muravyov, "Николай Муравьёв", "м").
персона(nikolai_punin, "Николай Пунин", "м").
персона(nikolai_avksentev, "Николай Авксентьев", "м").
персона(aleksei_polivanov, "Алексей Поливанов", "м").
персона(mikhail_belyaev, "Михаил Беляев", "м").
персона(aleksandr_bogdanov_malinovskii, "Александр Богданов-Малиновский", "м").
персона(tatyana_shchepkina_kupernik, "Татьяна Щепкина-Куперник", "ж").
персона(grigorii_petnikov, "Григорий Петников", "м").
персона(georgii_chulkov, "Георгий Чулков", "м").
персона(sofya_tolstaya, "Софья Толстая", "ж").
персона(david_burlyuk, "Давид Бурлюк", "м").
персона(vera_sudeikina, "Вера Судейкина", "ж").
персона(iosif_stalin, "Иосиф Сталин", "м").
персона(mikhail_grushevskii, "Михаил Грушевский", "м").
персона(valerii_bryusov, "Валерий Брюсов", "м").
персона(vladimir_girshman, "Владимир Гиршман", "м").
персона(ivan_shmelev, "Иван Шмелев", "м").
персона(vladimir_tatlin, "Владимир Татлин", "м").
персона(yulii_martov, "Юлий Мартов", "м").
персона(aleksandra_kublitskaya_piottukh, "Александра Кублицкая-Пиоттух", "ж").
персона(kamo_ter_petrosyan, "Камо Тер-Петросян", "м").
персона(iza_kremer, "Иза Кремер", "м").
персона(mikhail_zoshchenko, "Михаил Зощенко", "м").
персона(alisa_koonen, "Алиса Коонен", "м").
персона(mariya_ulyanova, "Мария Ульянова", "ж").
персона(kseniya_chizh, "Ксения Чиж", "ж").
персона(sergei_trubetskoi, "Сергей Трубецкой", "м").
персона(ivan_manukhin, "Иван Манухин", "м").
персона(nikolai_sukhanov, "Николай Суханов", "м").
персона(nikolai_chkheidze, "Николай Чхеидзе", "м").
персона(mark_shagal, "Марк Шагал", "м").
персона(boris_eikhenbaum, "Борис Эйхенбаум", "м").
персона(aleksei_putilov, "Алексей Путилов", "м").
персона(aleksandr_lukomskii, "Александр Лукомский", "м").
персона(nikolai_podvoiskii, "Николай Подвойский", "м").
персона(pavel_florenskii, "Павел Флоренский", "м").
персона(yelena_kirienko_voloshina, "Елена Кириенко-Волошина", "ж").
персона(vladimir_voeikov, "Владимир Воейков", "м").
персона(grigorii_trubetskoi, "Григорий Трубецкой", "м").
персона(vladimir_bonch_bruevich, "Владимир Бонч-Бруевич", "м").
персона(sergei_yefremov, "Сергей Ефремов", "м").
персона(sofiya_parnok, "София Парнок", "ж").
персона(anastasiya_tsvetaeva, "Анастасия Цветаева", "ж").
персона(nikolai_guchkov, "Николай Гучков", "м").
персона(andrei_shingarev, "Андрей Шингарев", "м").
персона(vera_kholodnaya, "Вера Холодная", "ж").
персона(boris_savinkov, "Борис Савинков", "м").
персона(viktor_adler, "Виктор Адлер", "м").
персона(aleksei_shakhmatov, "Алексей Шахматов", "м").
персона(sergei_efron, "Сергей Эфрон", "м").
персона(yekaterina_peshkova, "Екатерина Пешкова", "ж").
персона(irina_yusupova, "Ирина Юсупова", "ж").
персона(eduard_fuks, "Эдуард Фукс", "м").
персона(vasilii_gurko, "Василий Гурко", "м").
персона(nikolai_vrangel, "Николай Врангель", "м").
персона(aleksandr_kuprin, "Александр Куприн", "м").
персона(andrei_belii, "Андрей Белый", "м").
персона(georgii_ivanov, "Георгий Иванов", "м").
персона(mikhail_alekseev, "Михаил Алексеев", "м").
персона(aleksandr_golovin, "Александр Головин", "м").
персона(larisa_reisner, "Лариса Рейснер", "ж").
персона(nikolai_semashko, "Николай Семашко", "м").
персона(mikhail_bulgakov, "Михаил Булгаков", "м").
персона(serzh_lifar, "Серж Лифарь", "м").
персона(petr_voikov, "Петр Войков", "м").
персона(aleksandr_rodchenko, "Александр Родченко", "м").
персона(dmitrii_verderevskii, "Дмитрий Вердеревский", "м").
персона(mariya_andreeva, "Мария Андреева", "ж").
персона(sergei_grigorev, "Сергей Григорьев", "м").
персона(aleksandr_ern, "Александр Эрн", "м").
персона(demyan_bednii, "Демьян Бедный", "м").
персона(tatyana_sukhotina_tolstaya, "Татьяна Сухотина-Толстая", "ж").
персона(lyubov_gritsenko, "Любовь Гриценко", "ж").
персона(leonid_pasternak, "Леонид Пастернак", "м").
персона(praskovya_ivanovskaya, "Прасковья Ивановская", "ж").
персона(petr_struve, "Петр Струве", "м").
персона(lilya_brik, "Лиля Брик", "ж").
персона(zinaida_gippius, "Зинаида Гиппиус", "ж").
персона(fedor_kokoshkin, "Федор Кокошкин", "м").
персона(nadezhda_teffi, "Надежда Тэффи", "ж").
персона(fedor_shalyapin, "Федор Шаляпин", "м").
персона(aleksei_tolstoi, "Алексей Толстой", "м").
персона(sergei_bobrov, "Сергей Бобров", "м").
персона(vadim_shershenevich, "Вадим Шершеневич", "м").
персона(petr_kropotkin, "Петр Кропоткин", "м").
персона(mikhail_bonch_bruevich, "Михаил Бонч-Бруевич", "м").
персона(mariya_bochkareva, "Мария Бочкарева", "ж").
персона(aleksei_brusilov, "Алексей Брусилов", "м").
персона(aleksandr_konovalov, "Александр Коновалов", "м").
персона(kirill_narishkin, "Кирилл Нарышкин", "м").
персона(sergei_makovskii, "Сергей Маковский", "м").
персона(konstantin_guchkov, "Константин Гучков", "м").
персона(fedor_dan, "Федор Дан", "м").
персона(andrei_snesarev, "Андрей Снесарев", "м").
персона(yure_sirola, "Юрье Сирола", "м").
персона(vladimir_palei, "Владимир Палей", "м").
персона(rozaliya_pasternak, "Розалия Пастернак", "ж").
персона(vladimir_korolenko, "Владимир Короленко", "м").
персона(yelizaveta_time, "Елизавета Тиме", "ж").
персона(vladimir_nemirovich_danchenko, "Владимир Немирович-Данченко", "м").
персона(konstantin_somov, "Константин Сомов", "м").
персона(grigorii_rasputin, "Григорий Распутин", "м").
персона(petr_konchalovskii, "Петр Кончаловский", "м").
персона(sergei_yesenin, "Сергей Есенин", "м").
персона(pavel_milyukov, "Павел Милюков", "м").
персона(olga_zbarskaya, "Ольга Збарская", "ж").
персона(olga_glebova_sudeikina, "Ольга Глебова-Судейкина", "ж").
персона(pavel_benkendorf, "Павел Бенкендорф", "м").
персона(kornei_chukovskii, "Корней Чуковский", "м").
персона(mikhail_matyushin, "Михаил Матюшин", "м").
персона(aleksandr_benua, "Александр Бенуа", "м").
персона(boris_nikolskii, "Борис Никольский", "м").
персона(yekaterina_balmont, "Екатерина Бальмонт", "ж").
персона(felitsiya_bauer, "Фелиция Бауэр", "ж").
персона(aleksandr_trepov, "Александр Трепов", "м").
персона(yevgenii_zamyatin, "Евгений Замятин", "м").
персона(lyubov_popova, "Любовь Попова", "ж").
персона(mikhail_fokin, "Михаил Фокин", "м").
персона(mariya_baryatinskaya, "Мария Барятинская", "ж").
персона(sofya_vasilchikova, "Софья Васильчикова", "ж").
персона(kazimir_malevich, "Казимир Малевич", "м").
персона(velimir_khlebnikov, "Велимир Хлебников", "м").
персона(iosif_gessen, "Иосиф Гессен", "м").
персона(aristarkh_lentulov, "Аристарх Лентулов", "м").
персона(yekaterina_breshko_breshkovskaya, "Екатерина Брешко-Брешковская", "ж").
персона(anna_virubova, "Анна Вырубова", "ж").
персона(pavel_antokolskii, "Павел Антокольский", "м").
персона(valentin_kataev, "Валентин Катаев", "м").
персона(ivan_bunin, "Иван Бунин", "м").
персона(yepiskop_isidor, "Епископ Исидор", "м").
персона(vera_efron, "Вера Эфрон", "ж").
персона(nikolai_nekrasov, "Николай Некрасов", "м").
персона(aisedora_dunkan, "Айседора Дункан", "ж").
персона(tamara_karsavina, "Тамара Карсавина", "ж").
персона(yakov_sverdlov, "Яков Свердлов", "м").
персона(mikhail_tereshchenko, "Михаил Терещенко", "м").
персона(anna_lunacharskaya, "Анна Луначарская", "ж").
персона(anton_komashko, "Антон Комашко", "м").
персона(aleksei_aladin, "Алексей Аладьин", "м").
персона(inessa_armand, "Инесса Арманд", "ж").
персона(aleksei_zherebkov, "Алексей Жеребков", "м").
персона(marina_tsvetaeva, "Марина Цветаева", "ж").
персона(viktor_shklovskii, "Виктор Шкловский", "м").
персона(vladimir_purishkevich, "Владимир Пуришкевич", "м").
персона(yevno_azef, "Евно Азеф", "м").
персона(aleksandra_statsenko, "Александра Стаценко", "ж").
персона(vera_figner, "Вера Фигнер", "ж").
персона(varvara_stepanova, "Варвара Степанова", "ж").
персона(konstantin_paustovskii, "Константин Паустовский", "м").
персона(lidiya_pasternak, "Лидия Пастернак", "ж").
персона(dmitrii_filosofov, "Дмитрий Философов", "м").
персона(leonid_myasin, "Леонид Мясин", "м").
персона(anzhelika_balabanova, "Анжелика Балабанова", "ж").
персона(leonid_munshtein, "Леонид Мунштейн", "м").
персона(vera_kerbits_kerbitskaya, "Вера Кербиц-Кербицкая", "ж").
персона(aleksandra_ekster, "Александра Экстер", "ж").
персона(anna_timireva, "Анна Тимирева", "ж").
персона(vasilii_kamenskii, "Василий Каменский", "м").
персона(ivan_sitin, "Иван Сытин", "м").
персона(nikolai_rerikh, "Николай Рерих", "м").
персона(vladimir_antonov_ovseenko, "Владимир Антонов-Овсеенко", "м").
персона(valerii_mamontov, "Валерий Мамонтов", "м").
персона(maksimilian_voloshin, "Максимилиан Волошин", "м").
персона(anna_pavlova, "Анна Павлова", "ж").
персона(zinaida_yusupova, "Зинаида Юсупова", "ж").
персона(sasha_chernii, "Саша Черный", "м").
персона(razumnik_ivanov_razumnik, "Разумник Иванов-Разумник", "м").
персона(vladimir_burlyuk, "Владимир Бурлюк", "м").
персона(feliks_yusupov, "Феликс Юсупов", "м").
персона(yakub_ganetskii, "Якуб Ганецкий", "м").
персона(vasilii_shulgin, "Василий Шульгин", "м").
персона(sergei_eizenshtein, "Сергей Эйзенштейн", "м").
персона(ivan_shcheglovitov, "Иван Щегловитов", "м").
персона(sergei_sukhotin, "Сергей Сухотин", "м").
персона(anatolii_koni, "Анатолий Кони", "м").
персона(vatslav_nizhinskii, "Вацлав Нижинский", "м").
персона(vasilii_dolgorukov, "Василий Долгоруков", "м").
персона(velikaya_knyazhna_mariya, "Великая княжна Мария", "ж").
персона(vladimir_frederiks, "Владимир Фредерикс", "м").
персона(aleksandr_kerenskii, "Александр Керенский", "м").
персона(konstantin_stanislavskii, "Константин Станиславский", "м").
персона(mariya_petrova_vodkina, "Мария Петрова-Водкина", "ж").
персона(aleksei_remizov, "Алексей Ремизов", "м").
персона(nikolai_gumilev, "Николай Гумилев", "м").
персона(aleksandra_kollontai, "Александра Коллонтай", "ж").
персона(margarita_morozova, "Маргарита Морозова", "ж").
персона(pavel_dibenko, "Павел Дыбенко", "м").
персона(anna_akhmatova, "Анна Ахматова", "ж").
персона(anna_allilueva, "Анна Аллилуева", "ж").
персона(osip_mandelshtam, "Осип Мандельштам", "м").
персона(aleksandr_kolchak, "Александр Колчак", "м").
персона(nikolai_bukharin, "Николай Бухарин", "м").
персона(vladimir_dzhunkovskii, "Владимир Джунковский", "м").
персона(aleksandr_tyulkin, "Александр Тюлькин", "м").
персона(mariya_guchkova, "Мария Гучкова", "ж").
персона(yelizaveta_kuzmina_karavaeva, "Елизавета Кузьмина-Караваева", "ж").
персона(nikolai_ruzskii, "Николай Рузский", "м").
персона(leonid_krasin, "Леонид Красин", "м").
персона(vladimir_vernadskii, "Владимир Вернадский", "м").
персона(nikolai_stasyuk, "Николай Стасюк", "м").
персона(kuzma_petrov_vodkin, "Кузьма Петров-Водкин", "м").
персона(yurii_tinyanov, "Юрий Тынянов", "м").
персона(vladimir_lenin, "Владимир Ленин", "м").
персона(aleksei_ignatev, "Алексей Игнатьев", "м").
персона(razumnik_ivanov_razumnik, "Разумник Иванов-Разумник", "м").
персона(olga_rozanova, "Ольга Розанова", "ж").
персона(anna_stravinskaya, "Анна Стравинская", "ж").
персона(ottokar_chernin, "Оттокар Чернин", "м").
персона(ryurik_ivnev, "Рюрик Ивнев", "м").
персона(vladimir_burtsev, "Владимир Бурцев", "м").
персона(kliment_timiryazev, "Климент Тимирязев", "м").
персона(vyacheslav_karpinskii, "Вячеслав Карпинский", "м").
персона(nikolai_ryabushinskii, "Николай Рябушинский", "м").
персона(georgii_shavelskii, "Георгий Шавельский", "м").
персона(aleksandr_vertinskii, "Александр Вертинский", "м").
персона(valentina_zoshchenko, "Валентина Зощенко", "м").
персона(mikhail_nesterov, "Михаил Нестеров", "м").
персона(alla_nazimova, "Алла Назимова", "ж").
персона(yurii_annenkov, "Юрий Анненков", "м").
персона(mikhail_rodzyanko, "Михаил Родзянко", "м").
персона(vladimir_nemirovich_danchenko, "Владимир Немирович-Данченко", "м").
персона(vera_inber, "Вера Инбер", "ж").
персона(anna_chulkova, "Анна Чулкова", "ж").
персона(vladimir_sukhomlinov, "Владимир Сухомлинов", "м").
персона(marius_petipa, "Мариус Петипа", "м").
персона(nikolai_ivanov, "Николай Иванов", "м").
персона(nataliya_staritskaya, "Наталия Старицкая", "ж").
персона(vera_nemchinova, "Вера Немчинова", "ж").
персона(aleksandr_blok, "Александр Блок", "м").
персона(aleksei_kaledin, "Алексей Каледин", "м").
персона(feliks_yusupov_starshii, "Феликс Юсупов-старший", "м").
персона(mstislav_dobuzhinskii, "Мстислав Добужинский", "м").
персона(nestor_makhno, "Нестор Махно", "м").
персона(yelena_zoshchenko, "Елена Зощенко", "ж").
персона(georgii_plekhanov, "Георгий Плеханов", "м").
персона(ilya_repin, "Илья Репин", "м").
персона(kuzma_petrov_vodkin, "Кузьма Петров-Водкин", "м").
персона(sergei_prokofev, "Сергей Прокофьев", "м").
персона(yuliya_den, "Юлия Ден", "ж").
персона(zhozefina_pasternak, "Жозефина Пастернак", "ж").
