персона(lev_gumilev, "Лев Гумилев", "м").
персона(vlas_doroshevich, "Влас Дорошевич", "м").
персона(dmitrii_merezhkovskii, "Дмитрий Мережковский", "м").
персона(tatyana_shchepkina-kupernik, "Татьяна Щепкина-Куперник", "ж").
персона(marina_tsvetaeva, "Марина Цветаева", "ж").
персона(mikhail_gershenzon, "Михаил Гершензон", "м").
персона(vsevolod_meierkhold, "Всеволод Мейерхольд", "м").
персона(ilya_erenburg, "Илья Эренбург", "м").
персона(vera_kholodnaya, "Вера Холодная", "ж").
персона(boris_savinkov, "Борис Савинков", "м").
персона(leonid_andreev, "Леонид Андреев", "м").
персона(mikhail_lozinskii, "Михаил Лозинский", "м").
персона(konstantin_paustovskii, "Константин Паустовский", "м").
персона(anatolii_mariengof, "Анатолий Мариенгоф", "м").
персона(boris_anrep, "Борис Анреп", "м").
персона(dmitrii_filosofov, "Дмитрий Философов", "м").
персона(konstantin_balmont, "Константин Бальмонт", "м").
персона(leonid_myasin, "Леонид Мясин", "м").
персона(sergei_efron, "Сергей Эфрон", "м").
персона(andrei_belii, "Андрей Белый", "м").
персона(fedor_sologub, "Федор Сологуб", "м").
персона(georgii_ivanov, "Георгий Иванов", "м").
персона(vasilii_kandinskii, "Василий Кандинский", "м").
персона(el_lisitskii, "Эль Лисицкий", "м").
персона(aleksandra_ekster, "Александра Экстер", "ж").
персона(vasilii_kamenskii, "Василий Каменский", "м").
персона(vladislav_khodasevich, "Владислав Ходасевич", "м").
персона(boris_kustodiev, "Борис Кустодиев", "м").
персона(nikolai_rerikh, "Николай Рерих", "м").
персона(osip_brik, "Осип Брик", "м").
персона(vladimir_mayakovskii, "Владимир Маяковский", "м").
персона(vladimir_nabokov, "Владимир Набоков", "м").
персона(maksimilian_voloshin, "Максимилиан Волошин", "м").
персона(sergei_bulgakov, "Сергей Булгаков", "м").
персона(aleksei_kruchenikh, "Алексей Крученых", "м").
персона(mikhail_bulgakov, "Михаил Булгаков", "м").
персона(sergei_sudeikin, "Сергей Судейкин", "м").
персона(aleksandr_rodchenko, "Александр Родченко", "м").
персона(leonid_sobinov, "Леонид Собинов", "м").
персона(boris_pasternak, "Борис Пастернак", "м").
персона(demyan_bednii, "Демьян Бедный", "м").
персона(sergei_eizenshtein, "Сергей Эйзенштейн", "м").
персона(lilya_brik, "Лиля Брик", "ж").
персона(zinaida_gippius, "Зинаида Гиппиус", "ж").
персона(nadezhda_teffi, "Надежда Тэффи", "ж").
персона(fedor_shalyapin, "Федор Шаляпин", "м").
персона(aleksei_tolstoi, "Алексей Толстой", "м").
персона(aleksei_remizov, "Алексей Ремизов", "м").
персона(nikolai_gumilev, "Николай Гумилев", "м").
персона(vyacheslav_ivanov, "Вячеслав Иванов", "м").
персона(ivan_bilibin, "Иван Билибин", "м").
персона(natalya_goncharova, "Наталья Гончарова", "ж").
персона(anna_akhmatova, "Анна Ахматова", "ж").
персона(osip_mandelshtam, "Осип Мандельштам", "м").
персона(lev_bakst, "Лев Бакст", "м").
персона(nikolai_klyuev, "Николай Клюев", "м").
персона(igor_grabar, "Игорь Грабарь", "м").
персона(mikhail_larionov, "Михаил Ларионов", "м").
персона(igor_stravinskii, "Игорь Стравинский", "м").
персона(arkadii_averchenko, "Аркадий Аверченко", "м").
персона(sergei_makovskii, "Сергей Маковский", "м").
персона(sergei_rakhmaninov, "Сергей Рахманинов", "м").
персона(mikhail_prishvin, "Михаил Пришвин", "м").
персона(benedikt_livshits, "Бенедикт Лившиц", "м").
персона(nikolai_berdyaev, "Николай Бердяев", "м").
персона(anatolii_lunacharskii, "Анатолий Луначарский", "м").
персона(vladimir_gilyarovskii, "Владимир Гиляровский", "м").
персона(yevgenii_vakhtangov, "Евгений Вахтангов", "м").
персона(igor_severyanin, "Игорь Северянин", "м").
персона(vasilii_rozanov, "Василий Розанов", "м").
персона(nikolai_punin, "Николай Пунин", "м").
персона(vladimir_korolenko, "Владимир Короленко", "м").
персона(georgii_adamovich, "Георгий Адамович", "м").
персона(vladimir_nemirovich-danchenko, "Владимир Немирович-Данченко", "м").
персона(konstantin_somov, "Константин Сомов", "м").
персона(petr_konchalovskii, "Петр Кончаловский", "м").
персона(sergei_yesenin, "Сергей Есенин", "м").
персона(razumnik_ivanov-razumnik, "Разумник Иванов-Разумник", "м").
персона(aleksandr_amfiteatrov, "Александр Амфитеатров", "м").
персона(ryurik_ivnev, "Рюрик Ивнев", "м").
персона(valerii_bryusov, "Валерий Брюсов", "м").
персона(kornei_chukovskii, "Корней Чуковский", "м").
персона(aleksandr_benua, "Александр Бенуа", "м").
персона(ivan_shmelev, "Иван Шмелев", "м").
персона(vladimir_tatlin, "Владимир Татлин", "м").
персона(aleksandr_vertinskii, "Александр Вертинский", "м").
персона(yevgenii_zamyatin, "Евгений Замятин", "м").
персона(lyubov_popova, "Любовь Попова", "ж").
персона(mikhail_fokin, "Михаил Фокин", "м").
персона(yurii_annenkov, "Юрий Анненков", "м").
персона(mikhail_zoshchenko, "Михаил Зощенко", "м").
персона(kazimir_malevich, "Казимир Малевич", "м").
персона(velimir_khlebnikov, "Велимир Хлебников", "м").
персона(aristarkh_lentulov, "Аристарх Лентулов", "м").
персона(sergei_dyagilev, "Сергей Дягилев", "м").
персона(valentin_kataev, "Валентин Катаев", "м").
персона(ivan_bunin, "Иван Бунин", "м").
персона(mikhail_kuzmin, "Михаил Кузмин", "м").
персона(mark_shagal, "Марк Шагал", "м").
персона(maksim_gorkii, "Максим Горький", "м").
персона(aleksandr_blok, "Александр Блок", "м").
персона(yelizaveta_kuzmina-karavaeva, "Елизавета Кузьмина-Караваева", "ж").
персона(ilya_repin, "Илья Репин", "м").
персона(kuzma_petrov-vodkin, "Кузьма Петров-Водкин", "м").
персона(sergei_prokofev, "Сергей Прокофьев", "м").
персона(pavel_florenskii, "Павел Флоренский", "м").
